{"name": "test_greater_than_5[3]", "status": "failed", "statusDetails": {"message": "AssertionError: given number is not greater than 5\nassert False", "trace": "data = 3\n\n    @pytest.mark.parametrize(\"data\", [8,5,6,3])\n    def test_greater_than_5(data):\n        if data>5:\n            assert True\n        else:\n>           assert False, \"given number is not greater than 5\"\nE           AssertionError: given number is not greater than 5\nE           assert False\n\ntest_multiplication.py:20: AssertionError"}, "parameters": [{"name": "data", "value": "3"}], "start": 1670926054722, "stop": 1670926054722, "uuid": "a5e07b9c-5a52-480b-8e59-1b208e18f0ce", "historyId": "c5e2df0b5c856f92164d1a7f98e44352", "testCaseId": "7b32a898751e357258809f21e20a9edc", "fullName": "test_multiplication#test_greater_than_5", "labels": [{"name": "suite", "value": "test_multiplication"}, {"name": "host", "value": "DESKTOP-D9P5RJB"}, {"name": "thread", "value": "14116-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_multiplication"}]}