{"name": "test_greater_than_5[5]", "status": "failed", "statusDetails": {"message": "AssertionError: given number is not greater than 5\nassert False", "trace": "data = 5\n\n    @pytest.mark.parametrize(\"data\", [8,5,6,3])\n    def test_greater_than_5(data):\n        if data>5:\n            assert True\n        else:\n>           assert False, \"given number is not greater than 5\"\nE           AssertionError: given number is not greater than 5\nE           assert False\n\ntest_multiplication.py:20: AssertionError"}, "parameters": [{"name": "data", "value": "5"}], "start": 1670925497106, "stop": 1670925497106, "uuid": "b679f79b-f554-4087-9c43-a5a38264c26e", "historyId": "c70760970ab23685c9eb269b03d43c03", "testCaseId": "7b32a898751e357258809f21e20a9edc", "fullName": "test_multiplication#test_greater_than_5", "labels": [{"name": "suite", "value": "test_multiplication"}, {"name": "host", "value": "DESKTOP-D9P5RJB"}, {"name": "thread", "value": "9164-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_multiplication"}]}